# Generated by Django 2.0.7 on 2018-08-06 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plates', '0002_auto_20180801_1154'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='owner',
            unique_together={('first_name', 'last_name')},
        ),
    ]
